# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 708aabf8d639ac4de8d75967dd7668368c31cfe5a90d6e1606412e64e9f15c102659908fa520e61b0cedb1970e6c87569d8f947175fc3e117fd834e813d8986f

test:
  secret_key_base: 4c401fdfbe3b383fbffad2aa7b04a6d4ad87ea277b2b581afc64ec16163d6f3876606fb8c757b7fc15e240f8472d197418724af2ba85a2c9820e5165a48f2068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
